// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SimonRichardson/cluster/pkg/cluster (interfaces: Peer)

package mocks

import (
	cluster "github.com/SimonRichardson/cluster/pkg/cluster"
	members "github.com/SimonRichardson/cluster/pkg/members"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPeer is a mock of Peer interface
type MockPeer struct {
	ctrl     *gomock.Controller
	recorder *MockPeerMockRecorder
}

// MockPeerMockRecorder is the mock recorder for MockPeer
type MockPeerMockRecorder struct {
	mock *MockPeer
}

// NewMockPeer creates a new mock instance
func NewMockPeer(ctrl *gomock.Controller) *MockPeer {
	mock := &MockPeer{ctrl: ctrl}
	mock.recorder = &MockPeerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockPeer) EXPECT() *MockPeerMockRecorder {
	return _m.recorder
}

// Close mocks base method
func (_m *MockPeer) Close() {
	_m.ctrl.Call(_m, "Close")
}

// Close indicates an expected call of Close
func (_mr *MockPeerMockRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Close", reflect.TypeOf((*MockPeer)(nil).Close))
}

// ClusterSize mocks base method
func (_m *MockPeer) ClusterSize() int {
	ret := _m.ctrl.Call(_m, "ClusterSize")
	ret0, _ := ret[0].(int)
	return ret0
}

// ClusterSize indicates an expected call of ClusterSize
func (_mr *MockPeerMockRecorder) ClusterSize() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ClusterSize", reflect.TypeOf((*MockPeer)(nil).ClusterSize))
}

// Current mocks base method
func (_m *MockPeer) Current(_param0 members.PeerType) ([]string, error) {
	ret := _m.ctrl.Call(_m, "Current", _param0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current
func (_mr *MockPeerMockRecorder) Current(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Current", reflect.TypeOf((*MockPeer)(nil).Current), arg0)
}

// Join mocks base method
func (_m *MockPeer) Join() (int, error) {
	ret := _m.ctrl.Call(_m, "Join")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Join indicates an expected call of Join
func (_mr *MockPeerMockRecorder) Join() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Join", reflect.TypeOf((*MockPeer)(nil).Join))
}

// Leave mocks base method
func (_m *MockPeer) Leave() error {
	ret := _m.ctrl.Call(_m, "Leave")
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave
func (_mr *MockPeerMockRecorder) Leave() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Leave", reflect.TypeOf((*MockPeer)(nil).Leave))
}

// Listen mocks base method
func (_m *MockPeer) Listen(_param0 func(cluster.Reason)) error {
	ret := _m.ctrl.Call(_m, "Listen", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Listen indicates an expected call of Listen
func (_mr *MockPeerMockRecorder) Listen(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Listen", reflect.TypeOf((*MockPeer)(nil).Listen), arg0)
}

// Name mocks base method
func (_m *MockPeer) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockPeerMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Name", reflect.TypeOf((*MockPeer)(nil).Name))
}

// State mocks base method
func (_m *MockPeer) State() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "State")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// State indicates an expected call of State
func (_mr *MockPeerMockRecorder) State() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "State", reflect.TypeOf((*MockPeer)(nil).State))
}
